/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsolicitedSubmissionsRouteImport } from './routes/unsolicited-submissions'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionPolicyRouteImport } from './routes/subscription-policy'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DsarRouteImport } from './routes/dsar'
import { Route as DarkerAgesRouteImport } from './routes/darker-ages'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as CopyrightDmcaRouteImport } from './routes/copyright-dmca'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContentAccessibilityRouteImport } from './routes/content-accessibility'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as ChildrenOfAquariusRouteImport } from './routes/children-of-aquarius'
import { Route as CanonCameoTermsRouteImport } from './routes/canon-cameo-terms'
import { Route as BattlefieldAtlantisRouteImport } from './routes/battlefield-atlantis'
import { Route as AstralnautStudiosRouteImport } from './routes/astralnaut-studios'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SweepstakesRulesRouteImport } from './routes/sweepstakes.rules'
import { Route as SweepstakesFreeEntryRouteImport } from './routes/sweepstakes.free-entry'
import { Route as RaffleRulesRouteImport } from './routes/raffle.rules'
import { Route as RaffleFreeEntryRouteImport } from './routes/raffle.free-entry'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as LearnModuleIdRouteImport } from './routes/learn.$moduleId'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as DsarVerifyRouteImport } from './routes/dsar.verify'
import { Route as ArchiveWalletRouteImport } from './routes/archive.wallet'
import { Route as ArchiveTimelineRouteImport } from './routes/archive.timeline'
import { Route as ArchiveQuartermasterRouteImport } from './routes/archive.quartermaster'
import { Route as ArchivePersonnelRouteImport } from './routes/archive.personnel'
import { Route as ArchiveEvidenceRouteImport } from './routes/archive.evidence'
import { Route as ArchiveDocumentsRouteImport } from './routes/archive.documents'
import { Route as ArchiveDatabaseRouteImport } from './routes/archive.database'
import { Route as ArchiveClearanceRouteImport } from './routes/archive.clearance'
import { Route as ArchiveBriefingsRouteImport } from './routes/archive.briefings'
import { Route as AuthenticatedGrowthPackageRouteImport } from './routes/_authenticated/growth-package'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ReaderSeriesIssueRouteImport } from './routes/reader.$series.$issue'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicGameEventsRouteImport } from './routes/api/public/game-events'
import { Route as AuthenticatedCommunityJoinRouteImport } from './routes/_authenticated/community.join'
import { Route as AuthenticatedCameoSubmitRouteImport } from './routes/_authenticated/cameo.submit'
import { Route as AuthenticatedAdminVisitorsRouteImport } from './routes/_authenticated/admin.visitors'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionTestRouteImport } from './routes/_authenticated/admin.subscription-test'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLettersRouteImport } from './routes/_authenticated/admin.letters'
import { Route as AuthenticatedAdminLearnRouteImport } from './routes/_authenticated/admin.learn'
import { Route as AuthenticatedAdminHelpRouteImport } from './routes/_authenticated/admin.help'
import { Route as AuthenticatedAdminComplianceChangelogRouteImport } from './routes/_authenticated/admin.compliance-changelog'
import { Route as AuthenticatedAdminAuthorFaqRouteImport } from './routes/_authenticated/admin.author-faq'
import { Route as AuthenticatedAdminAuthorBioRouteImport } from './routes/_authenticated/admin.author-bio'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicLeadsUnsubscribeRouteImport } from './routes/api/public/leads/unsubscribe'
import { Route as ApiPublicLeadsConfirmRouteImport } from './routes/api/public/leads/confirm'
import { Route as ApiPublicCronRetentionRouteImport } from './routes/api/public/cron/retention'
import { Route as ApiPublicCronRenewalRemindersRouteImport } from './routes/api/public/cron/renewal-reminders'
import { Route as AuthenticatedAdminLearnModuleIdRouteImport } from './routes/_authenticated/admin.learn.$moduleId'
import { Route as AuthenticatedAdminHelpSlugRouteImport } from './routes/_authenticated/admin.help.$slug'
import { Route as AuthenticatedReaderSeriesIssueLettersRouteImport } from './routes/_authenticated/reader.$series.$issue.letters'

const UnsolicitedSubmissionsRoute = UnsolicitedSubmissionsRouteImport.update({
  id: '/unsolicited-submissions',
  path: '/unsolicited-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionPolicyRoute = SubscriptionPolicyRouteImport.update({
  id: '/subscription-policy',
  path: '/subscription-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DsarRoute = DsarRouteImport.update({
  id: '/dsar',
  path: '/dsar',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkerAgesRoute = DarkerAgesRouteImport.update({
  id: '/darker-ages',
  path: '/darker-ages',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightDmcaRoute = CopyrightDmcaRouteImport.update({
  id: '/copyright-dmca',
  path: '/copyright-dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentAccessibilityRoute = ContentAccessibilityRouteImport.update({
  id: '/content-accessibility',
  path: '/content-accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenOfAquariusRoute = ChildrenOfAquariusRouteImport.update({
  id: '/children-of-aquarius',
  path: '/children-of-aquarius',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonCameoTermsRoute = CanonCameoTermsRouteImport.update({
  id: '/canon-cameo-terms',
  path: '/canon-cameo-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlefieldAtlantisRoute = BattlefieldAtlantisRouteImport.update({
  id: '/battlefield-atlantis',
  path: '/battlefield-atlantis',
  getParentRoute: () => rootRouteImport,
} as any)
const AstralnautStudiosRoute = AstralnautStudiosRouteImport.update({
  id: '/astralnaut-studios',
  path: '/astralnaut-studios',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepstakesRulesRoute = SweepstakesRulesRouteImport.update({
  id: '/sweepstakes/rules',
  path: '/sweepstakes/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepstakesFreeEntryRoute = SweepstakesFreeEntryRouteImport.update({
  id: '/sweepstakes/free-entry',
  path: '/sweepstakes/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRulesRoute = RaffleRulesRouteImport.update({
  id: '/raffle/rules',
  path: '/raffle/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleFreeEntryRoute = RaffleFreeEntryRouteImport.update({
  id: '/raffle/free-entry',
  path: '/raffle/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnModuleIdRoute = LearnModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearnRoute,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const DsarVerifyRoute = DsarVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DsarRoute,
} as any)
const ArchiveWalletRoute = ArchiveWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveTimelineRoute = ArchiveTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveQuartermasterRoute = ArchiveQuartermasterRouteImport.update({
  id: '/quartermaster',
  path: '/quartermaster',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchivePersonnelRoute = ArchivePersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveEvidenceRoute = ArchiveEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveDocumentsRoute = ArchiveDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveDatabaseRoute = ArchiveDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveClearanceRoute = ArchiveClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveBriefingsRoute = ArchiveBriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => ArchiveRoute,
} as any)
const AuthenticatedGrowthPackageRoute =
  AuthenticatedGrowthPackageRouteImport.update({
    id: '/growth-package',
    path: '/growth-package',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ReaderSeriesIssueRoute = ReaderSeriesIssueRouteImport.update({
  id: '/reader/$series/$issue',
  path: '/reader/$series/$issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGameEventsRoute = ApiPublicGameEventsRouteImport.update({
  id: '/api/public/game-events',
  path: '/api/public/game-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunityJoinRoute =
  AuthenticatedCommunityJoinRouteImport.update({
    id: '/community/join',
    path: '/community/join',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCameoSubmitRoute =
  AuthenticatedCameoSubmitRouteImport.update({
    id: '/cameo/submit',
    path: '/cameo/submit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVisitorsRoute =
  AuthenticatedAdminVisitorsRouteImport.update({
    id: '/admin/visitors',
    path: '/admin/visitors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSubscriptionTestRoute =
  AuthenticatedAdminSubscriptionTestRouteImport.update({
    id: '/admin/subscription-test',
    path: '/admin/subscription-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminLettersRoute =
  AuthenticatedAdminLettersRouteImport.update({
    id: '/admin/letters',
    path: '/admin/letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLearnRoute = AuthenticatedAdminLearnRouteImport.update({
  id: '/admin/learn',
  path: '/admin/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminHelpRoute = AuthenticatedAdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminComplianceChangelogRoute =
  AuthenticatedAdminComplianceChangelogRouteImport.update({
    id: '/admin/compliance-changelog',
    path: '/admin/compliance-changelog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuthorFaqRoute =
  AuthenticatedAdminAuthorFaqRouteImport.update({
    id: '/admin/author-faq',
    path: '/admin/author-faq',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuthorBioRoute =
  AuthenticatedAdminAuthorBioRouteImport.update({
    id: '/admin/author-bio',
    path: '/admin/author-bio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsUnsubscribeRoute =
  ApiPublicLeadsUnsubscribeRouteImport.update({
    id: '/api/public/leads/unsubscribe',
    path: '/api/public/leads/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsConfirmRoute = ApiPublicLeadsConfirmRouteImport.update({
  id: '/api/public/leads/confirm',
  path: '/api/public/leads/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRetentionRoute = ApiPublicCronRetentionRouteImport.update({
  id: '/api/public/cron/retention',
  path: '/api/public/cron/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRenewalRemindersRoute =
  ApiPublicCronRenewalRemindersRouteImport.update({
    id: '/api/public/cron/renewal-reminders',
    path: '/api/public/cron/renewal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminLearnModuleIdRoute =
  AuthenticatedAdminLearnModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedAdminLearnRoute,
  } as any)
const AuthenticatedAdminHelpSlugRoute =
  AuthenticatedAdminHelpSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAdminHelpRoute,
  } as any)
const AuthenticatedReaderSeriesIssueLettersRoute =
  AuthenticatedReaderSeriesIssueLettersRouteImport.update({
    id: '/reader/$series/$issue/letters',
    path: '/reader/$series/$issue/letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/canon-cameo-terms': typeof CanonCameoTermsRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/content-accessibility': typeof ContentAccessibilityRoute
  '/cookies': typeof CookiesRoute
  '/copyright-dmca': typeof CopyrightDmcaRoute
  '/corporate': typeof CorporateRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/dsar': typeof DsarRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsolicited-submissions': typeof UnsolicitedSubmissionsRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/archive/briefings': typeof ArchiveBriefingsRoute
  '/archive/clearance': typeof ArchiveClearanceRoute
  '/archive/database': typeof ArchiveDatabaseRoute
  '/archive/documents': typeof ArchiveDocumentsRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/archive/personnel': typeof ArchivePersonnelRoute
  '/archive/quartermaster': typeof ArchiveQuartermasterRoute
  '/archive/timeline': typeof ArchiveTimelineRoute
  '/archive/wallet': typeof ArchiveWalletRoute
  '/dsar/verify': typeof DsarVerifyRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/sweepstakes/free-entry': typeof SweepstakesFreeEntryRoute
  '/sweepstakes/rules': typeof SweepstakesRulesRoute
  '/admin/author-bio': typeof AuthenticatedAdminAuthorBioRoute
  '/admin/author-faq': typeof AuthenticatedAdminAuthorFaqRoute
  '/admin/compliance-changelog': typeof AuthenticatedAdminComplianceChangelogRoute
  '/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/cameo/submit': typeof AuthenticatedCameoSubmitRoute
  '/community/join': typeof AuthenticatedCommunityJoinRoute
  '/api/public/game-events': typeof ApiPublicGameEventsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/cron/renewal-reminders': typeof ApiPublicCronRenewalRemindersRoute
  '/api/public/cron/retention': typeof ApiPublicCronRetentionRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/canon-cameo-terms': typeof CanonCameoTermsRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/content-accessibility': typeof ContentAccessibilityRoute
  '/cookies': typeof CookiesRoute
  '/copyright-dmca': typeof CopyrightDmcaRoute
  '/corporate': typeof CorporateRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/dsar': typeof DsarRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsolicited-submissions': typeof UnsolicitedSubmissionsRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/archive/briefings': typeof ArchiveBriefingsRoute
  '/archive/clearance': typeof ArchiveClearanceRoute
  '/archive/database': typeof ArchiveDatabaseRoute
  '/archive/documents': typeof ArchiveDocumentsRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/archive/personnel': typeof ArchivePersonnelRoute
  '/archive/quartermaster': typeof ArchiveQuartermasterRoute
  '/archive/timeline': typeof ArchiveTimelineRoute
  '/archive/wallet': typeof ArchiveWalletRoute
  '/dsar/verify': typeof DsarVerifyRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/sweepstakes/free-entry': typeof SweepstakesFreeEntryRoute
  '/sweepstakes/rules': typeof SweepstakesRulesRoute
  '/admin/author-bio': typeof AuthenticatedAdminAuthorBioRoute
  '/admin/author-faq': typeof AuthenticatedAdminAuthorFaqRoute
  '/admin/compliance-changelog': typeof AuthenticatedAdminComplianceChangelogRoute
  '/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/cameo/submit': typeof AuthenticatedCameoSubmitRoute
  '/community/join': typeof AuthenticatedCommunityJoinRoute
  '/api/public/game-events': typeof ApiPublicGameEventsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/cron/renewal-reminders': typeof ApiPublicCronRenewalRemindersRoute
  '/api/public/cron/retention': typeof ApiPublicCronRetentionRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/canon-cameo-terms': typeof CanonCameoTermsRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/content-accessibility': typeof ContentAccessibilityRoute
  '/cookies': typeof CookiesRoute
  '/copyright-dmca': typeof CopyrightDmcaRoute
  '/corporate': typeof CorporateRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/dsar': typeof DsarRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/subscription-policy': typeof SubscriptionPolicyRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/unsolicited-submissions': typeof UnsolicitedSubmissionsRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/archive/briefings': typeof ArchiveBriefingsRoute
  '/archive/clearance': typeof ArchiveClearanceRoute
  '/archive/database': typeof ArchiveDatabaseRoute
  '/archive/documents': typeof ArchiveDocumentsRoute
  '/archive/evidence': typeof ArchiveEvidenceRoute
  '/archive/personnel': typeof ArchivePersonnelRoute
  '/archive/quartermaster': typeof ArchiveQuartermasterRoute
  '/archive/timeline': typeof ArchiveTimelineRoute
  '/archive/wallet': typeof ArchiveWalletRoute
  '/dsar/verify': typeof DsarVerifyRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/sweepstakes/free-entry': typeof SweepstakesFreeEntryRoute
  '/sweepstakes/rules': typeof SweepstakesRulesRoute
  '/_authenticated/admin/author-bio': typeof AuthenticatedAdminAuthorBioRoute
  '/_authenticated/admin/author-faq': typeof AuthenticatedAdminAuthorFaqRoute
  '/_authenticated/admin/compliance-changelog': typeof AuthenticatedAdminComplianceChangelogRoute
  '/_authenticated/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/_authenticated/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/_authenticated/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/_authenticated/cameo/submit': typeof AuthenticatedCameoSubmitRoute
  '/_authenticated/community/join': typeof AuthenticatedCommunityJoinRoute
  '/api/public/game-events': typeof ApiPublicGameEventsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/_authenticated/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/cron/renewal-reminders': typeof ApiPublicCronRenewalRemindersRoute
  '/api/public/cron/retention': typeof ApiPublicCronRetentionRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/archive'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/canon-cameo-terms'
    | '/children-of-aquarius'
    | '/community-guidelines'
    | '/content-accessibility'
    | '/cookies'
    | '/copyright-dmca'
    | '/corporate'
    | '/darker-ages'
    | '/dsar'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/subscription-policy'
    | '/terms'
    | '/trust'
    | '/unsolicited-submissions'
    | '/growth'
    | '/growth-package'
    | '/archive/briefings'
    | '/archive/clearance'
    | '/archive/database'
    | '/archive/documents'
    | '/archive/evidence'
    | '/archive/personnel'
    | '/archive/quartermaster'
    | '/archive/timeline'
    | '/archive/wallet'
    | '/dsar/verify'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/sweepstakes/free-entry'
    | '/sweepstakes/rules'
    | '/admin/author-bio'
    | '/admin/author-faq'
    | '/admin/compliance-changelog'
    | '/admin/help'
    | '/admin/learn'
    | '/admin/letters'
    | '/admin/media'
    | '/admin/security'
    | '/admin/subscription-test'
    | '/admin/users'
    | '/admin/visitors'
    | '/cameo/submit'
    | '/community/join'
    | '/api/public/game-events'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/admin/'
    | '/admin/help/$slug'
    | '/admin/learn/$moduleId'
    | '/api/public/cron/renewal-reminders'
    | '/api/public/cron/retention'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/reader/$series/$issue/letters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/archive'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/canon-cameo-terms'
    | '/children-of-aquarius'
    | '/community-guidelines'
    | '/content-accessibility'
    | '/cookies'
    | '/copyright-dmca'
    | '/corporate'
    | '/darker-ages'
    | '/dsar'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/subscription-policy'
    | '/terms'
    | '/trust'
    | '/unsolicited-submissions'
    | '/growth'
    | '/growth-package'
    | '/archive/briefings'
    | '/archive/clearance'
    | '/archive/database'
    | '/archive/documents'
    | '/archive/evidence'
    | '/archive/personnel'
    | '/archive/quartermaster'
    | '/archive/timeline'
    | '/archive/wallet'
    | '/dsar/verify'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/sweepstakes/free-entry'
    | '/sweepstakes/rules'
    | '/admin/author-bio'
    | '/admin/author-faq'
    | '/admin/compliance-changelog'
    | '/admin/help'
    | '/admin/learn'
    | '/admin/letters'
    | '/admin/media'
    | '/admin/security'
    | '/admin/subscription-test'
    | '/admin/users'
    | '/admin/visitors'
    | '/cameo/submit'
    | '/community/join'
    | '/api/public/game-events'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/admin'
    | '/admin/help/$slug'
    | '/admin/learn/$moduleId'
    | '/api/public/cron/renewal-reminders'
    | '/api/public/cron/retention'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/reader/$series/$issue/letters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/archive'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/canon-cameo-terms'
    | '/children-of-aquarius'
    | '/community-guidelines'
    | '/content-accessibility'
    | '/cookies'
    | '/copyright-dmca'
    | '/corporate'
    | '/darker-ages'
    | '/dsar'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/privacy'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/subscription-policy'
    | '/terms'
    | '/trust'
    | '/unsolicited-submissions'
    | '/_authenticated/growth'
    | '/_authenticated/growth-package'
    | '/archive/briefings'
    | '/archive/clearance'
    | '/archive/database'
    | '/archive/documents'
    | '/archive/evidence'
    | '/archive/personnel'
    | '/archive/quartermaster'
    | '/archive/timeline'
    | '/archive/wallet'
    | '/dsar/verify'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/sweepstakes/free-entry'
    | '/sweepstakes/rules'
    | '/_authenticated/admin/author-bio'
    | '/_authenticated/admin/author-faq'
    | '/_authenticated/admin/compliance-changelog'
    | '/_authenticated/admin/help'
    | '/_authenticated/admin/learn'
    | '/_authenticated/admin/letters'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/subscription-test'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/visitors'
    | '/_authenticated/cameo/submit'
    | '/_authenticated/community/join'
    | '/api/public/game-events'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/help/$slug'
    | '/_authenticated/admin/learn/$moduleId'
    | '/api/public/cron/renewal-reminders'
    | '/api/public/cron/retention'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/_authenticated/reader/$series/$issue/letters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountRoute: typeof AccountRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  AstralnautStudiosRoute: typeof AstralnautStudiosRoute
  BattlefieldAtlantisRoute: typeof BattlefieldAtlantisRoute
  CanonCameoTermsRoute: typeof CanonCameoTermsRoute
  ChildrenOfAquariusRoute: typeof ChildrenOfAquariusRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContentAccessibilityRoute: typeof ContentAccessibilityRoute
  CookiesRoute: typeof CookiesRoute
  CopyrightDmcaRoute: typeof CopyrightDmcaRoute
  CorporateRoute: typeof CorporateRoute
  DarkerAgesRoute: typeof DarkerAgesRoute
  DsarRoute: typeof DsarRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  IndustryRoute: typeof IndustryRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  PerksRoute: typeof PerksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  SubscriptionPolicyRoute: typeof SubscriptionPolicyRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  UnsolicitedSubmissionsRoute: typeof UnsolicitedSubmissionsRoute
  ProductHandleRoute: typeof ProductHandleRoute
  RaffleFreeEntryRoute: typeof RaffleFreeEntryRoute
  RaffleRulesRoute: typeof RaffleRulesRoute
  SweepstakesFreeEntryRoute: typeof SweepstakesFreeEntryRoute
  SweepstakesRulesRoute: typeof SweepstakesRulesRoute
  ApiPublicGameEventsRoute: typeof ApiPublicGameEventsRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ReaderSeriesIssueRoute: typeof ReaderSeriesIssueRoute
  ApiPublicCronRenewalRemindersRoute: typeof ApiPublicCronRenewalRemindersRoute
  ApiPublicCronRetentionRoute: typeof ApiPublicCronRetentionRoute
  ApiPublicLeadsConfirmRoute: typeof ApiPublicLeadsConfirmRoute
  ApiPublicLeadsUnsubscribeRoute: typeof ApiPublicLeadsUnsubscribeRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsolicited-submissions': {
      id: '/unsolicited-submissions'
      path: '/unsolicited-submissions'
      fullPath: '/unsolicited-submissions'
      preLoaderRoute: typeof UnsolicitedSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-policy': {
      id: '/subscription-policy'
      path: '/subscription-policy'
      fullPath: '/subscription-policy'
      preLoaderRoute: typeof SubscriptionPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsar': {
      id: '/dsar'
      path: '/dsar'
      fullPath: '/dsar'
      preLoaderRoute: typeof DsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darker-ages': {
      id: '/darker-ages'
      path: '/darker-ages'
      fullPath: '/darker-ages'
      preLoaderRoute: typeof DarkerAgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-dmca': {
      id: '/copyright-dmca'
      path: '/copyright-dmca'
      fullPath: '/copyright-dmca'
      preLoaderRoute: typeof CopyrightDmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-accessibility': {
      id: '/content-accessibility'
      path: '/content-accessibility'
      fullPath: '/content-accessibility'
      preLoaderRoute: typeof ContentAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children-of-aquarius': {
      id: '/children-of-aquarius'
      path: '/children-of-aquarius'
      fullPath: '/children-of-aquarius'
      preLoaderRoute: typeof ChildrenOfAquariusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon-cameo-terms': {
      id: '/canon-cameo-terms'
      path: '/canon-cameo-terms'
      fullPath: '/canon-cameo-terms'
      preLoaderRoute: typeof CanonCameoTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlefield-atlantis': {
      id: '/battlefield-atlantis'
      path: '/battlefield-atlantis'
      fullPath: '/battlefield-atlantis'
      preLoaderRoute: typeof BattlefieldAtlantisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astralnaut-studios': {
      id: '/astralnaut-studios'
      path: '/astralnaut-studios'
      fullPath: '/astralnaut-studios'
      preLoaderRoute: typeof AstralnautStudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweepstakes/rules': {
      id: '/sweepstakes/rules'
      path: '/sweepstakes/rules'
      fullPath: '/sweepstakes/rules'
      preLoaderRoute: typeof SweepstakesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweepstakes/free-entry': {
      id: '/sweepstakes/free-entry'
      path: '/sweepstakes/free-entry'
      fullPath: '/sweepstakes/free-entry'
      preLoaderRoute: typeof SweepstakesFreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle/rules': {
      id: '/raffle/rules'
      path: '/raffle/rules'
      fullPath: '/raffle/rules'
      preLoaderRoute: typeof RaffleRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle/free-entry': {
      id: '/raffle/free-entry'
      path: '/raffle/free-entry'
      fullPath: '/raffle/free-entry'
      preLoaderRoute: typeof RaffleFreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$moduleId': {
      id: '/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof LearnModuleIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/dsar/verify': {
      id: '/dsar/verify'
      path: '/verify'
      fullPath: '/dsar/verify'
      preLoaderRoute: typeof DsarVerifyRouteImport
      parentRoute: typeof DsarRoute
    }
    '/archive/wallet': {
      id: '/archive/wallet'
      path: '/wallet'
      fullPath: '/archive/wallet'
      preLoaderRoute: typeof ArchiveWalletRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/timeline': {
      id: '/archive/timeline'
      path: '/timeline'
      fullPath: '/archive/timeline'
      preLoaderRoute: typeof ArchiveTimelineRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/quartermaster': {
      id: '/archive/quartermaster'
      path: '/quartermaster'
      fullPath: '/archive/quartermaster'
      preLoaderRoute: typeof ArchiveQuartermasterRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/personnel': {
      id: '/archive/personnel'
      path: '/personnel'
      fullPath: '/archive/personnel'
      preLoaderRoute: typeof ArchivePersonnelRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/evidence': {
      id: '/archive/evidence'
      path: '/evidence'
      fullPath: '/archive/evidence'
      preLoaderRoute: typeof ArchiveEvidenceRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/documents': {
      id: '/archive/documents'
      path: '/documents'
      fullPath: '/archive/documents'
      preLoaderRoute: typeof ArchiveDocumentsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/database': {
      id: '/archive/database'
      path: '/database'
      fullPath: '/archive/database'
      preLoaderRoute: typeof ArchiveDatabaseRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/clearance': {
      id: '/archive/clearance'
      path: '/clearance'
      fullPath: '/archive/clearance'
      preLoaderRoute: typeof ArchiveClearanceRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/briefings': {
      id: '/archive/briefings'
      path: '/briefings'
      fullPath: '/archive/briefings'
      preLoaderRoute: typeof ArchiveBriefingsRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/_authenticated/growth-package': {
      id: '/_authenticated/growth-package'
      path: '/growth-package'
      fullPath: '/growth-package'
      preLoaderRoute: typeof AuthenticatedGrowthPackageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/reader/$series/$issue': {
      id: '/reader/$series/$issue'
      path: '/reader/$series/$issue'
      fullPath: '/reader/$series/$issue'
      preLoaderRoute: typeof ReaderSeriesIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/game-events': {
      id: '/api/public/game-events'
      path: '/api/public/game-events'
      fullPath: '/api/public/game-events'
      preLoaderRoute: typeof ApiPublicGameEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/join': {
      id: '/_authenticated/community/join'
      path: '/community/join'
      fullPath: '/community/join'
      preLoaderRoute: typeof AuthenticatedCommunityJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cameo/submit': {
      id: '/_authenticated/cameo/submit'
      path: '/cameo/submit'
      fullPath: '/cameo/submit'
      preLoaderRoute: typeof AuthenticatedCameoSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/visitors': {
      id: '/_authenticated/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AuthenticatedAdminVisitorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscription-test': {
      id: '/_authenticated/admin/subscription-test'
      path: '/admin/subscription-test'
      fullPath: '/admin/subscription-test'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/letters': {
      id: '/_authenticated/admin/letters'
      path: '/admin/letters'
      fullPath: '/admin/letters'
      preLoaderRoute: typeof AuthenticatedAdminLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/learn': {
      id: '/_authenticated/admin/learn'
      path: '/admin/learn'
      fullPath: '/admin/learn'
      preLoaderRoute: typeof AuthenticatedAdminLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/help': {
      id: '/_authenticated/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AuthenticatedAdminHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/compliance-changelog': {
      id: '/_authenticated/admin/compliance-changelog'
      path: '/admin/compliance-changelog'
      fullPath: '/admin/compliance-changelog'
      preLoaderRoute: typeof AuthenticatedAdminComplianceChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/author-faq': {
      id: '/_authenticated/admin/author-faq'
      path: '/admin/author-faq'
      fullPath: '/admin/author-faq'
      preLoaderRoute: typeof AuthenticatedAdminAuthorFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/author-bio': {
      id: '/_authenticated/admin/author-bio'
      path: '/admin/author-bio'
      fullPath: '/admin/author-bio'
      preLoaderRoute: typeof AuthenticatedAdminAuthorBioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/unsubscribe': {
      id: '/api/public/leads/unsubscribe'
      path: '/api/public/leads/unsubscribe'
      fullPath: '/api/public/leads/unsubscribe'
      preLoaderRoute: typeof ApiPublicLeadsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/confirm': {
      id: '/api/public/leads/confirm'
      path: '/api/public/leads/confirm'
      fullPath: '/api/public/leads/confirm'
      preLoaderRoute: typeof ApiPublicLeadsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/retention': {
      id: '/api/public/cron/retention'
      path: '/api/public/cron/retention'
      fullPath: '/api/public/cron/retention'
      preLoaderRoute: typeof ApiPublicCronRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/renewal-reminders': {
      id: '/api/public/cron/renewal-reminders'
      path: '/api/public/cron/renewal-reminders'
      fullPath: '/api/public/cron/renewal-reminders'
      preLoaderRoute: typeof ApiPublicCronRenewalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/learn/$moduleId': {
      id: '/_authenticated/admin/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/admin/learn/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminLearnModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminLearnRoute
    }
    '/_authenticated/admin/help/$slug': {
      id: '/_authenticated/admin/help/$slug'
      path: '/$slug'
      fullPath: '/admin/help/$slug'
      preLoaderRoute: typeof AuthenticatedAdminHelpSlugRouteImport
      parentRoute: typeof AuthenticatedAdminHelpRoute
    }
    '/_authenticated/reader/$series/$issue/letters': {
      id: '/_authenticated/reader/$series/$issue/letters'
      path: '/reader/$series/$issue/letters'
      fullPath: '/reader/$series/$issue/letters'
      preLoaderRoute: typeof AuthenticatedReaderSeriesIssueLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminHelpRouteChildren {
  AuthenticatedAdminHelpSlugRoute: typeof AuthenticatedAdminHelpSlugRoute
}

const AuthenticatedAdminHelpRouteChildren: AuthenticatedAdminHelpRouteChildren =
  {
    AuthenticatedAdminHelpSlugRoute: AuthenticatedAdminHelpSlugRoute,
  }

const AuthenticatedAdminHelpRouteWithChildren =
  AuthenticatedAdminHelpRoute._addFileChildren(
    AuthenticatedAdminHelpRouteChildren,
  )

interface AuthenticatedAdminLearnRouteChildren {
  AuthenticatedAdminLearnModuleIdRoute: typeof AuthenticatedAdminLearnModuleIdRoute
}

const AuthenticatedAdminLearnRouteChildren: AuthenticatedAdminLearnRouteChildren =
  {
    AuthenticatedAdminLearnModuleIdRoute: AuthenticatedAdminLearnModuleIdRoute,
  }

const AuthenticatedAdminLearnRouteWithChildren =
  AuthenticatedAdminLearnRoute._addFileChildren(
    AuthenticatedAdminLearnRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedGrowthPackageRoute: typeof AuthenticatedGrowthPackageRoute
  AuthenticatedAdminAuthorBioRoute: typeof AuthenticatedAdminAuthorBioRoute
  AuthenticatedAdminAuthorFaqRoute: typeof AuthenticatedAdminAuthorFaqRoute
  AuthenticatedAdminComplianceChangelogRoute: typeof AuthenticatedAdminComplianceChangelogRoute
  AuthenticatedAdminHelpRoute: typeof AuthenticatedAdminHelpRouteWithChildren
  AuthenticatedAdminLearnRoute: typeof AuthenticatedAdminLearnRouteWithChildren
  AuthenticatedAdminLettersRoute: typeof AuthenticatedAdminLettersRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSubscriptionTestRoute: typeof AuthenticatedAdminSubscriptionTestRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVisitorsRoute: typeof AuthenticatedAdminVisitorsRoute
  AuthenticatedCameoSubmitRoute: typeof AuthenticatedCameoSubmitRoute
  AuthenticatedCommunityJoinRoute: typeof AuthenticatedCommunityJoinRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedReaderSeriesIssueLettersRoute: typeof AuthenticatedReaderSeriesIssueLettersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedGrowthPackageRoute: AuthenticatedGrowthPackageRoute,
  AuthenticatedAdminAuthorBioRoute: AuthenticatedAdminAuthorBioRoute,
  AuthenticatedAdminAuthorFaqRoute: AuthenticatedAdminAuthorFaqRoute,
  AuthenticatedAdminComplianceChangelogRoute:
    AuthenticatedAdminComplianceChangelogRoute,
  AuthenticatedAdminHelpRoute: AuthenticatedAdminHelpRouteWithChildren,
  AuthenticatedAdminLearnRoute: AuthenticatedAdminLearnRouteWithChildren,
  AuthenticatedAdminLettersRoute: AuthenticatedAdminLettersRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSubscriptionTestRoute:
    AuthenticatedAdminSubscriptionTestRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVisitorsRoute: AuthenticatedAdminVisitorsRoute,
  AuthenticatedCameoSubmitRoute: AuthenticatedCameoSubmitRoute,
  AuthenticatedCommunityJoinRoute: AuthenticatedCommunityJoinRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedReaderSeriesIssueLettersRoute:
    AuthenticatedReaderSeriesIssueLettersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ArchiveRouteChildren {
  ArchiveBriefingsRoute: typeof ArchiveBriefingsRoute
  ArchiveClearanceRoute: typeof ArchiveClearanceRoute
  ArchiveDatabaseRoute: typeof ArchiveDatabaseRoute
  ArchiveDocumentsRoute: typeof ArchiveDocumentsRoute
  ArchiveEvidenceRoute: typeof ArchiveEvidenceRoute
  ArchivePersonnelRoute: typeof ArchivePersonnelRoute
  ArchiveQuartermasterRoute: typeof ArchiveQuartermasterRoute
  ArchiveTimelineRoute: typeof ArchiveTimelineRoute
  ArchiveWalletRoute: typeof ArchiveWalletRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveBriefingsRoute: ArchiveBriefingsRoute,
  ArchiveClearanceRoute: ArchiveClearanceRoute,
  ArchiveDatabaseRoute: ArchiveDatabaseRoute,
  ArchiveDocumentsRoute: ArchiveDocumentsRoute,
  ArchiveEvidenceRoute: ArchiveEvidenceRoute,
  ArchivePersonnelRoute: ArchivePersonnelRoute,
  ArchiveQuartermasterRoute: ArchiveQuartermasterRoute,
  ArchiveTimelineRoute: ArchiveTimelineRoute,
  ArchiveWalletRoute: ArchiveWalletRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface DsarRouteChildren {
  DsarVerifyRoute: typeof DsarVerifyRoute
}

const DsarRouteChildren: DsarRouteChildren = {
  DsarVerifyRoute: DsarVerifyRoute,
}

const DsarRouteWithChildren = DsarRoute._addFileChildren(DsarRouteChildren)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface LearnRouteChildren {
  LearnModuleIdRoute: typeof LearnModuleIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnModuleIdRoute: LearnModuleIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountRoute: AccountRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  AstralnautStudiosRoute: AstralnautStudiosRoute,
  BattlefieldAtlantisRoute: BattlefieldAtlantisRoute,
  CanonCameoTermsRoute: CanonCameoTermsRoute,
  ChildrenOfAquariusRoute: ChildrenOfAquariusRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContentAccessibilityRoute: ContentAccessibilityRoute,
  CookiesRoute: CookiesRoute,
  CopyrightDmcaRoute: CopyrightDmcaRoute,
  CorporateRoute: CorporateRoute,
  DarkerAgesRoute: DarkerAgesRoute,
  DsarRoute: DsarRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  IndustryRoute: IndustryRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  PerksRoute: PerksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  SubscriptionPolicyRoute: SubscriptionPolicyRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  UnsolicitedSubmissionsRoute: UnsolicitedSubmissionsRoute,
  ProductHandleRoute: ProductHandleRoute,
  RaffleFreeEntryRoute: RaffleFreeEntryRoute,
  RaffleRulesRoute: RaffleRulesRoute,
  SweepstakesFreeEntryRoute: SweepstakesFreeEntryRoute,
  SweepstakesRulesRoute: SweepstakesRulesRoute,
  ApiPublicGameEventsRoute: ApiPublicGameEventsRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ReaderSeriesIssueRoute: ReaderSeriesIssueRoute,
  ApiPublicCronRenewalRemindersRoute: ApiPublicCronRenewalRemindersRoute,
  ApiPublicCronRetentionRoute: ApiPublicCronRetentionRoute,
  ApiPublicLeadsConfirmRoute: ApiPublicLeadsConfirmRoute,
  ApiPublicLeadsUnsubscribeRoute: ApiPublicLeadsUnsubscribeRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
