/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DarkerAgesRouteImport } from './routes/darker-ages'
import { Route as ChildrenOfAquariusRouteImport } from './routes/children-of-aquarius'
import { Route as BattlefieldAtlantisRouteImport } from './routes/battlefield-atlantis'
import { Route as AstralnautStudiosRouteImport } from './routes/astralnaut-studios'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaffleRulesRouteImport } from './routes/raffle.rules'
import { Route as RaffleFreeEntryRouteImport } from './routes/raffle.free-entry'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as LearnModuleIdRouteImport } from './routes/learn.$moduleId'
import { Route as HelpSlugRouteImport } from './routes/help.$slug'
import { Route as AuthenticatedGrowthPackageRouteImport } from './routes/_authenticated/growth-package'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ReaderSeriesIssueRouteImport } from './routes/reader.$series.$issue'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedAdminVisitorsRouteImport } from './routes/_authenticated/admin.visitors'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionTestRouteImport } from './routes/_authenticated/admin.subscription-test'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminLettersRouteImport } from './routes/_authenticated/admin.letters'
import { Route as AuthenticatedAdminLearnRouteImport } from './routes/_authenticated/admin.learn'
import { Route as AuthenticatedAdminHelpRouteImport } from './routes/_authenticated/admin.help'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicLeadsUnsubscribeRouteImport } from './routes/api/public/leads/unsubscribe'
import { Route as ApiPublicLeadsConfirmRouteImport } from './routes/api/public/leads/confirm'
import { Route as AuthenticatedAdminLearnModuleIdRouteImport } from './routes/_authenticated/admin.learn.$moduleId'
import { Route as AuthenticatedAdminHelpSlugRouteImport } from './routes/_authenticated/admin.help.$slug'
import { Route as AuthenticatedReaderSeriesIssueLettersRouteImport } from './routes/_authenticated/reader.$series.$issue.letters'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkerAgesRoute = DarkerAgesRouteImport.update({
  id: '/darker-ages',
  path: '/darker-ages',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenOfAquariusRoute = ChildrenOfAquariusRouteImport.update({
  id: '/children-of-aquarius',
  path: '/children-of-aquarius',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlefieldAtlantisRoute = BattlefieldAtlantisRouteImport.update({
  id: '/battlefield-atlantis',
  path: '/battlefield-atlantis',
  getParentRoute: () => rootRouteImport,
} as any)
const AstralnautStudiosRoute = AstralnautStudiosRouteImport.update({
  id: '/astralnaut-studios',
  path: '/astralnaut-studios',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRulesRoute = RaffleRulesRouteImport.update({
  id: '/raffle/rules',
  path: '/raffle/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleFreeEntryRoute = RaffleFreeEntryRouteImport.update({
  id: '/raffle/free-entry',
  path: '/raffle/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnModuleIdRoute = LearnModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => LearnRoute,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HelpRoute,
} as any)
const AuthenticatedGrowthPackageRoute =
  AuthenticatedGrowthPackageRouteImport.update({
    id: '/growth-package',
    path: '/growth-package',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ReaderSeriesIssueRoute = ReaderSeriesIssueRouteImport.update({
  id: '/reader/$series/$issue',
  path: '/reader/$series/$issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVisitorsRoute =
  AuthenticatedAdminVisitorsRouteImport.update({
    id: '/admin/visitors',
    path: '/admin/visitors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSubscriptionTestRoute =
  AuthenticatedAdminSubscriptionTestRouteImport.update({
    id: '/admin/subscription-test',
    path: '/admin/subscription-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLettersRoute =
  AuthenticatedAdminLettersRouteImport.update({
    id: '/admin/letters',
    path: '/admin/letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLearnRoute = AuthenticatedAdminLearnRouteImport.update({
  id: '/admin/learn',
  path: '/admin/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminHelpRoute = AuthenticatedAdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsUnsubscribeRoute =
  ApiPublicLeadsUnsubscribeRouteImport.update({
    id: '/api/public/leads/unsubscribe',
    path: '/api/public/leads/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsConfirmRoute = ApiPublicLeadsConfirmRouteImport.update({
  id: '/api/public/leads/confirm',
  path: '/api/public/leads/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLearnModuleIdRoute =
  AuthenticatedAdminLearnModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedAdminLearnRoute,
  } as any)
const AuthenticatedAdminHelpSlugRoute =
  AuthenticatedAdminHelpSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAdminHelpRoute,
  } as any)
const AuthenticatedReaderSeriesIssueLettersRoute =
  AuthenticatedReaderSeriesIssueLettersRouteImport.update({
    id: '/reader/$series/$issue/letters',
    path: '/reader/$series/$issue/letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/account': typeof AccountRoute
  '/astralnaut-studios': typeof AstralnautStudiosRoute
  '/battlefield-atlantis': typeof BattlefieldAtlantisRoute
  '/children-of-aquarius': typeof ChildrenOfAquariusRoute
  '/darker-ages': typeof DarkerAgesRoute
  '/help': typeof HelpRouteWithChildren
  '/industry': typeof IndustryRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/perks': typeof PerksRoute
  '/pricing': typeof PricingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/growth-package': typeof AuthenticatedGrowthPackageRoute
  '/help/$slug': typeof HelpSlugRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/raffle/free-entry': typeof RaffleFreeEntryRoute
  '/raffle/rules': typeof RaffleRulesRoute
  '/_authenticated/admin/help': typeof AuthenticatedAdminHelpRouteWithChildren
  '/_authenticated/admin/learn': typeof AuthenticatedAdminLearnRouteWithChildren
  '/_authenticated/admin/letters': typeof AuthenticatedAdminLettersRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/subscription-test': typeof AuthenticatedAdminSubscriptionTestRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/visitors': typeof AuthenticatedAdminVisitorsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/reader/$series/$issue': typeof ReaderSeriesIssueRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/help/$slug': typeof AuthenticatedAdminHelpSlugRoute
  '/_authenticated/admin/learn/$moduleId': typeof AuthenticatedAdminLearnModuleIdRoute
  '/api/public/leads/confirm': typeof ApiPublicLeadsConfirmRoute
  '/api/public/leads/unsubscribe': typeof ApiPublicLeadsUnsubscribeRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/reader/$series/$issue/letters': typeof AuthenticatedReaderSeriesIssueLettersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/children-of-aquarius'
    | '/darker-ages'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/shop'
    | '/sitemap.xml'
    | '/growth'
    | '/growth-package'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/admin/help'
    | '/admin/learn'
    | '/admin/letters'
    | '/admin/security'
    | '/admin/subscription-test'
    | '/admin/users'
    | '/admin/visitors'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/admin/'
    | '/admin/help/$slug'
    | '/admin/learn/$moduleId'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/reader/$series/$issue/letters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/children-of-aquarius'
    | '/darker-ages'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/shop'
    | '/sitemap.xml'
    | '/growth'
    | '/growth-package'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/admin/help'
    | '/admin/learn'
    | '/admin/letters'
    | '/admin/security'
    | '/admin/subscription-test'
    | '/admin/users'
    | '/admin/visitors'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/admin'
    | '/admin/help/$slug'
    | '/admin/learn/$moduleId'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/reader/$series/$issue/letters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/astralnaut-studios'
    | '/battlefield-atlantis'
    | '/children-of-aquarius'
    | '/darker-ages'
    | '/help'
    | '/industry'
    | '/learn'
    | '/login'
    | '/perks'
    | '/pricing'
    | '/shop'
    | '/sitemap.xml'
    | '/_authenticated/growth'
    | '/_authenticated/growth-package'
    | '/help/$slug'
    | '/learn/$moduleId'
    | '/product/$handle'
    | '/raffle/free-entry'
    | '/raffle/rules'
    | '/_authenticated/admin/help'
    | '/_authenticated/admin/learn'
    | '/_authenticated/admin/letters'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/subscription-test'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/visitors'
    | '/api/public/track'
    | '/reader/$series/$issue'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/help/$slug'
    | '/_authenticated/admin/learn/$moduleId'
    | '/api/public/leads/confirm'
    | '/api/public/leads/unsubscribe'
    | '/api/public/payments/webhook'
    | '/_authenticated/reader/$series/$issue/letters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccountRoute: typeof AccountRoute
  AstralnautStudiosRoute: typeof AstralnautStudiosRoute
  BattlefieldAtlantisRoute: typeof BattlefieldAtlantisRoute
  ChildrenOfAquariusRoute: typeof ChildrenOfAquariusRoute
  DarkerAgesRoute: typeof DarkerAgesRoute
  HelpRoute: typeof HelpRouteWithChildren
  IndustryRoute: typeof IndustryRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  PerksRoute: typeof PerksRoute
  PricingRoute: typeof PricingRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductHandleRoute: typeof ProductHandleRoute
  RaffleFreeEntryRoute: typeof RaffleFreeEntryRoute
  RaffleRulesRoute: typeof RaffleRulesRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ReaderSeriesIssueRoute: typeof ReaderSeriesIssueRoute
  ApiPublicLeadsConfirmRoute: typeof ApiPublicLeadsConfirmRoute
  ApiPublicLeadsUnsubscribeRoute: typeof ApiPublicLeadsUnsubscribeRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darker-ages': {
      id: '/darker-ages'
      path: '/darker-ages'
      fullPath: '/darker-ages'
      preLoaderRoute: typeof DarkerAgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children-of-aquarius': {
      id: '/children-of-aquarius'
      path: '/children-of-aquarius'
      fullPath: '/children-of-aquarius'
      preLoaderRoute: typeof ChildrenOfAquariusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlefield-atlantis': {
      id: '/battlefield-atlantis'
      path: '/battlefield-atlantis'
      fullPath: '/battlefield-atlantis'
      preLoaderRoute: typeof BattlefieldAtlantisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astralnaut-studios': {
      id: '/astralnaut-studios'
      path: '/astralnaut-studios'
      fullPath: '/astralnaut-studios'
      preLoaderRoute: typeof AstralnautStudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle/rules': {
      id: '/raffle/rules'
      path: '/raffle/rules'
      fullPath: '/raffle/rules'
      preLoaderRoute: typeof RaffleRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle/free-entry': {
      id: '/raffle/free-entry'
      path: '/raffle/free-entry'
      fullPath: '/raffle/free-entry'
      preLoaderRoute: typeof RaffleFreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$moduleId': {
      id: '/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof LearnModuleIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof HelpRoute
    }
    '/_authenticated/growth-package': {
      id: '/_authenticated/growth-package'
      path: '/growth-package'
      fullPath: '/growth-package'
      preLoaderRoute: typeof AuthenticatedGrowthPackageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/reader/$series/$issue': {
      id: '/reader/$series/$issue'
      path: '/reader/$series/$issue'
      fullPath: '/reader/$series/$issue'
      preLoaderRoute: typeof ReaderSeriesIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/visitors': {
      id: '/_authenticated/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AuthenticatedAdminVisitorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscription-test': {
      id: '/_authenticated/admin/subscription-test'
      path: '/admin/subscription-test'
      fullPath: '/admin/subscription-test'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/letters': {
      id: '/_authenticated/admin/letters'
      path: '/admin/letters'
      fullPath: '/admin/letters'
      preLoaderRoute: typeof AuthenticatedAdminLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/learn': {
      id: '/_authenticated/admin/learn'
      path: '/admin/learn'
      fullPath: '/admin/learn'
      preLoaderRoute: typeof AuthenticatedAdminLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/help': {
      id: '/_authenticated/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AuthenticatedAdminHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/unsubscribe': {
      id: '/api/public/leads/unsubscribe'
      path: '/api/public/leads/unsubscribe'
      fullPath: '/api/public/leads/unsubscribe'
      preLoaderRoute: typeof ApiPublicLeadsUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/confirm': {
      id: '/api/public/leads/confirm'
      path: '/api/public/leads/confirm'
      fullPath: '/api/public/leads/confirm'
      preLoaderRoute: typeof ApiPublicLeadsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/learn/$moduleId': {
      id: '/_authenticated/admin/learn/$moduleId'
      path: '/$moduleId'
      fullPath: '/admin/learn/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminLearnModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminLearnRoute
    }
    '/_authenticated/admin/help/$slug': {
      id: '/_authenticated/admin/help/$slug'
      path: '/$slug'
      fullPath: '/admin/help/$slug'
      preLoaderRoute: typeof AuthenticatedAdminHelpSlugRouteImport
      parentRoute: typeof AuthenticatedAdminHelpRoute
    }
    '/_authenticated/reader/$series/$issue/letters': {
      id: '/_authenticated/reader/$series/$issue/letters'
      path: '/reader/$series/$issue/letters'
      fullPath: '/reader/$series/$issue/letters'
      preLoaderRoute: typeof AuthenticatedReaderSeriesIssueLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminHelpRouteChildren {
  AuthenticatedAdminHelpSlugRoute: typeof AuthenticatedAdminHelpSlugRoute
}

const AuthenticatedAdminHelpRouteChildren: AuthenticatedAdminHelpRouteChildren =
  {
    AuthenticatedAdminHelpSlugRoute: AuthenticatedAdminHelpSlugRoute,
  }

const AuthenticatedAdminHelpRouteWithChildren =
  AuthenticatedAdminHelpRoute._addFileChildren(
    AuthenticatedAdminHelpRouteChildren,
  )

interface AuthenticatedAdminLearnRouteChildren {
  AuthenticatedAdminLearnModuleIdRoute: typeof AuthenticatedAdminLearnModuleIdRoute
}

const AuthenticatedAdminLearnRouteChildren: AuthenticatedAdminLearnRouteChildren =
  {
    AuthenticatedAdminLearnModuleIdRoute: AuthenticatedAdminLearnModuleIdRoute,
  }

const AuthenticatedAdminLearnRouteWithChildren =
  AuthenticatedAdminLearnRoute._addFileChildren(
    AuthenticatedAdminLearnRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedGrowthPackageRoute: typeof AuthenticatedGrowthPackageRoute
  AuthenticatedAdminHelpRoute: typeof AuthenticatedAdminHelpRouteWithChildren
  AuthenticatedAdminLearnRoute: typeof AuthenticatedAdminLearnRouteWithChildren
  AuthenticatedAdminLettersRoute: typeof AuthenticatedAdminLettersRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSubscriptionTestRoute: typeof AuthenticatedAdminSubscriptionTestRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVisitorsRoute: typeof AuthenticatedAdminVisitorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedReaderSeriesIssueLettersRoute: typeof AuthenticatedReaderSeriesIssueLettersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedGrowthPackageRoute: AuthenticatedGrowthPackageRoute,
  AuthenticatedAdminHelpRoute: AuthenticatedAdminHelpRouteWithChildren,
  AuthenticatedAdminLearnRoute: AuthenticatedAdminLearnRouteWithChildren,
  AuthenticatedAdminLettersRoute: AuthenticatedAdminLettersRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSubscriptionTestRoute:
    AuthenticatedAdminSubscriptionTestRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVisitorsRoute: AuthenticatedAdminVisitorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedReaderSeriesIssueLettersRoute:
    AuthenticatedReaderSeriesIssueLettersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HelpRouteChildren {
  HelpSlugRoute: typeof HelpSlugRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSlugRoute: HelpSlugRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface LearnRouteChildren {
  LearnModuleIdRoute: typeof LearnModuleIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnModuleIdRoute: LearnModuleIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccountRoute: AccountRoute,
  AstralnautStudiosRoute: AstralnautStudiosRoute,
  BattlefieldAtlantisRoute: BattlefieldAtlantisRoute,
  ChildrenOfAquariusRoute: ChildrenOfAquariusRoute,
  DarkerAgesRoute: DarkerAgesRoute,
  HelpRoute: HelpRouteWithChildren,
  IndustryRoute: IndustryRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  PerksRoute: PerksRoute,
  PricingRoute: PricingRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductHandleRoute: ProductHandleRoute,
  RaffleFreeEntryRoute: RaffleFreeEntryRoute,
  RaffleRulesRoute: RaffleRulesRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ReaderSeriesIssueRoute: ReaderSeriesIssueRoute,
  ApiPublicLeadsConfirmRoute: ApiPublicLeadsConfirmRoute,
  ApiPublicLeadsUnsubscribeRoute: ApiPublicLeadsUnsubscribeRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
