/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.output/server/wrangler.json --include-runtime=false src/worker-env.d.ts` (hash: eff037d92df7609786b3e16c5d93590b)
// Fetcher is module-qualified to avoid introducing Worker globals into the DOM app.
interface __BaseEnv_Env {
	ASSETS: import("@cloudflare/workers-types").Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
